# Generated by Django 3.2.19 on 2023-06-02 21:08

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1, help_text='Обязательное для заполнения поле. Минимальное количество ингредиентов - 1 шт.', validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиентов не может быть меньше одного')], verbose_name='Количество ингредиентов')),
            ],
            options={
                'verbose_name': 'Количество ингридиентов',
                'verbose_name_plural': 'Количество ингридиентов',
                'ordering': ('recipe',),
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранный рецепт',
                'verbose_name_plural': 'Избранные рецепты',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Обязательное для заполнение поле. Максимальная длинна 200 символов.', max_length=200, verbose_name='Название')),
                ('measurement_unit', models.CharField(help_text='Обязательное для заполнение поле. Максимальная длинна 200 символов.', max_length=200, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательное для заполнение поле. Максимальная длинна 200 символов.', max_length=200, verbose_name='Название')),
                ('text', models.TextField(help_text='Обязательное для заполнения поле.', validators=[api.validators.validate_clean_text], verbose_name='Описание')),
                ('image', models.ImageField(help_text='Обязательное для заполнения поле.', upload_to='images/', verbose_name='Картинка')),
                ('cooking_time', models.PositiveSmallIntegerField(default=1, help_text='Обязательное для заполнения поле. Минимальное время приготовления - 1 минута', validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не может быть меньше одной минуты')], verbose_name='Время приготовления (в минутах)')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательное для заполнение поле. Максимальная длинна 200 символов.', max_length=200, unique=True, validators=[api.validators.validate_clean_text], verbose_name='Название')),
                ('color', colorfield.fields.ColorField(default='#FF0000', help_text=('Обязательное для заполнение поле. Максимальная длинна 7 символов.',), image_field=None, max_length=7, samples=None, unique=True, verbose_name='HEX-код')),
                ('slug', models.SlugField(help_text='Обязательное для заполнение поле. Максимальная длинна 200 символов.', max_length=200, unique=True, verbose_name='Метка')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShopingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_shopingcart', to='recipes.recipe', verbose_name='Рецепт в списке покупок')),
            ],
            options={
                'verbose_name': 'Рецепт в списке покупок',
                'verbose_name_plural': 'Рецепты в списке покупок',
            },
        ),
    ]
