# Generated by Django 3.2.19 on 2023-06-02 22:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#00FF7F', 'Зелёный'), ('#FFD700', 'Жёлтый'), ('#00BFFF', 'Синий')], default='#FFFFFF', help_text=('Обязательное для заполнение поле. Максимальная длинна 7 символов.',), image_field=None, max_length=7, samples=None, unique=True, verbose_name='HEX-код'),
        ),
    ]
