# Generated by Django 3.2.19 on 2023-06-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230605_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredients',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
