# Generated by Django 3.2.19 on 2023-06-07 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_ingredient_unique_name_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, help_text='Обязательное для заполнения поле. Минимальное время приготовления - 1 минута', validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не может быть меньше одной минуты'), django.core.validators.MaxValueValidator(600, message='Время приготовления не может быть больше десяти часов')], verbose_name='Время приготовления (в минутах)'),
        ),
    ]
